Repository Breeding-Insight/bi-web, pull requests merged in 2024-01, with the labels that each got.

#352 [BI-1761] Error message with the backend code
  package-lock.json
  package.json
  src/components/notifications/ErrorNotification.vue
Labels: feature

#356 [BI-2036] Update guest accounts listed in Sandbox left sidebar nav menu
  src/components/layouts/InfoSideBarLayout.vue
Labels: hotfix

#355 BI-2005 - Expand Exp Template
  src/breeding-insight/model/DatasetTableRow.ts
  src/breeding-insight/model/GeoCoordinates.ts
  src/breeding-insight/model/ObservationUnit.ts
  src/views/import/Dataset.vue
  src/views/import/ImportExperiment.vue
Labels: feature

#357 BI-2029 (Experiment Preview and Visual Progress Indicators Broken in v0.90
  src/views/import/ImportExperiment.vue
Labels: bug

#346 BI-1921 - Support Field Book Study Import from DeltaBreed
  package-lock.json
  package.json
  src/router/index.ts
  src/views/BrAPI/BrAPIInfo.vue
Labels: feature
